-- =====================================================================
-- Pikmin Atlas (Nomad Atlas) — 초기 데이터베이스 구성
--   실행 위치: Supabase 대시보드 → SQL Editor → New query → 전체 붙여넣기 → Run
--   여러 번 실행해도 안전하도록(이미 있으면 건너뛰거나 다시 만듦) 작성했다.
--   이 파일에는 비밀 정보가 없다. 공개 저장소에 있어도 된다.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. 비공개 스키마: 주인 계정 지정 (API로 노출되지 않는 스키마)
-- ---------------------------------------------------------------------
create schema if not exists private;

-- 주인 계정은 딱 1명. singleton 열이 항상 true + unique 이므로 행이 2개가 될 수 없다.
create table if not exists private.app_owner (
  user_id   uuid primary key references auth.users (id) on delete cascade,
  singleton boolean not null default true unique check (singleton)
);
revoke all on private.app_owner from public, anon, authenticated;

-- 지금 로그인한 사람이 주인인가? (가입이 실수로 열려도 다른 계정은 아무것도 못 한다)
create or replace function private.is_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from private.app_owner o where o.user_id = auth.uid());
$$;
revoke all on function private.is_owner() from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.is_owner() to authenticated;

-- ---------------------------------------------------------------------
-- 1. 표
-- ---------------------------------------------------------------------
create table if not exists public.owner_settings (
  owner_id             uuid primary key default auth.uid() references auth.users (id) on delete cascade,
  password_initialized boolean not null default false,
  last_backup_at       timestamptz,
  schema_version       integer not null default 1,
  updated_at           timestamptz not null default now()
);

create table if not exists public.photos (
  id          uuid primary key default gen_random_uuid(),
  owner_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  kind        text not null check (kind in ('place', 'icon')),
  path        text not null,
  thumb_path  text,
  width       integer not null check (width > 0),
  height      integer not null check (height > 0),
  bytes       integer not null check (bytes >= 0),
  sha256      text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  created_at  timestamptz not null default now()
);

create table if not exists public.deco_categories (
  id             uuid primary key default gen_random_uuid(),
  owner_id       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name           text not null check (char_length(name) between 1 and 50 and name = btrim(name)),
  icon           text not null default '' check (char_length(icon) <= 16),
  icon_photo_id  uuid references public.photos (id) on delete restrict,
  sort_order     integer not null default 0,
  version        integer not null default 1,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz
);

create unique index if not exists deco_categories_name_unique
  on public.deco_categories (owner_id, lower(name))
  where deleted_at is null;

create table if not exists public.places (
  id                uuid primary key default gen_random_uuid(),
  owner_id          uuid not null default auth.uid() references auth.users (id) on delete cascade,
  category          text not null check (category in ('mushroom', 'bigflower', 'deco')),
  deco_category_id  uuid references public.deco_categories (id) on delete set null,
  name              text not null check (char_length(name) between 1 and 100 and name = btrim(name)),
  description       text not null default '' check (char_length(description) <= 2000),
  lat               double precision not null check (lat between -90 and 90),
  lng               double precision not null check (lng between -180 and 180),
  photo_id          uuid references public.photos (id) on delete restrict,
  is_favorite       boolean not null default false,
  seq               bigint generated by default as identity,
  version           integer not null default 1,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  constraint places_deco_only check (category = 'deco' or deco_category_id is null)
);

create index if not exists places_owner_category on public.places (owner_id, category, created_at desc);
create index if not exists places_photo on public.places (photo_id);
create index if not exists places_deco_category on public.places (deco_category_id);

create table if not exists public.restore_snapshots (
  id          uuid primary key default gen_random_uuid(),
  owner_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at  timestamptz not null default now(),
  status      text not null default 'pending'
              check (status in ('pending', 'committed', 'rolled_back', 'finalized', 'cancelled')),
  payload     jsonb not null,
  restored_photo_paths jsonb not null default '[]'::jsonb
);

-- ---------------------------------------------------------------------
-- 2. 수정 시각·버전 자동 갱신 (동시 수정 충돌 감지용)
-- ---------------------------------------------------------------------
create or replace function public.touch_row()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  new.version := old.version + 1;
  return new;
end;
$$;

drop trigger if exists places_touch on public.places;
create trigger places_touch before update on public.places
  for each row execute function public.touch_row();

drop trigger if exists deco_categories_touch on public.deco_categories;
create trigger deco_categories_touch before update on public.deco_categories
  for each row execute function public.touch_row();

-- ---------------------------------------------------------------------
-- 3. 권한: 비로그인(anon)에게는 표 권한 자체를 주지 않는다
-- ---------------------------------------------------------------------
revoke all on public.owner_settings, public.photos, public.deco_categories,
              public.places, public.restore_snapshots from anon, public;
grant select, insert, update, delete on public.owner_settings, public.photos,
      public.deco_categories, public.places, public.restore_snapshots to authenticated;

-- 복원 시 등록 순번 카운터를 맞추기 위한 권한
do $$
begin
  execute format('grant usage, select, update on sequence %s to authenticated',
                 pg_get_serial_sequence('public.places', 'seq'));
  execute format('revoke all on sequence %s from anon',
                 pg_get_serial_sequence('public.places', 'seq'));
end $$;

alter table public.owner_settings    enable row level security;
alter table public.photos            enable row level security;
alter table public.deco_categories   enable row level security;
alter table public.places            enable row level security;
alter table public.restore_snapshots enable row level security;

-- 표마다 같은 규칙: 로그인한 주인 본인 행만 읽기·쓰기
do $$
declare t text;
begin
  foreach t in array array['owner_settings','photos','deco_categories','places','restore_snapshots'] loop
    execute format('drop policy if exists owner_all on public.%I', t);
    execute format(
      'create policy owner_all on public.%I for all to authenticated
         using (owner_id = (select auth.uid()) and (select private.is_owner()))
         with check (owner_id = (select auth.uid()) and (select private.is_owner()))', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------
-- 4. 사진 저장소: 비공개 버킷 + 주인 폴더 정책
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('nomad-private', 'nomad-private', false, 5242880, array['image/jpeg', 'image/png'])
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "nomad owner read"   on storage.objects;
drop policy if exists "nomad owner insert" on storage.objects;
drop policy if exists "nomad owner update" on storage.objects;
drop policy if exists "nomad owner delete" on storage.objects;

create policy "nomad owner read" on storage.objects for select to authenticated
  using (bucket_id = 'nomad-private'
         and (storage.foldername(name))[1] = (select auth.uid())::text
         and (select private.is_owner()));
create policy "nomad owner insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'nomad-private'
         and (storage.foldername(name))[1] = (select auth.uid())::text
         and (select private.is_owner()));
create policy "nomad owner update" on storage.objects for update to authenticated
  using (bucket_id = 'nomad-private'
         and (storage.foldername(name))[1] = (select auth.uid())::text
         and (select private.is_owner()))
  with check (bucket_id = 'nomad-private'
         and (storage.foldername(name))[1] = (select auth.uid())::text
         and (select private.is_owner()));
create policy "nomad owner delete" on storage.objects for delete to authenticated
  using (bucket_id = 'nomad-private'
         and (storage.foldername(name))[1] = (select auth.uid())::text
         and (select private.is_owner()));

-- ---------------------------------------------------------------------
-- 5. 서버 함수 (모두 SECURITY INVOKER → 위 RLS가 그대로 적용됨)
-- ---------------------------------------------------------------------

-- 5-1. 주어진 사진 중 더 이상 아무도 쓰지 않는 사진 행을 지우고 파일 경로를 돌려준다
create or replace function public.gc_photos(candidate_ids uuid[])
returns text[]
language plpgsql
security invoker
set search_path = ''
as $$
declare paths text[];
begin
  with gone as (
    delete from public.photos ph
     where ph.id = any(candidate_ids)
       and not exists (select 1 from public.places p where p.photo_id = ph.id)
       and not exists (select 1 from public.deco_categories c where c.icon_photo_id = ph.id)
    returning ph.path, ph.thumb_path
  )
  select coalesce(array_agg(x) filter (where x is not null), '{}')
    into paths
    from gone, lateral unnest(array[gone.path, gone.thumb_path]) as x;
  return paths;
end;
$$;

-- 5-2. 휴지통의 장소 영구 삭제 → 지울 파일 경로 반환
create or replace function public.purge_places(ids uuid[])
returns text[]
language plpgsql
security invoker
set search_path = ''
as $$
declare photo_ids uuid[];
begin
  select coalesce(array_agg(distinct photo_id) filter (where photo_id is not null), '{}')
    into photo_ids
    from public.places where id = any(ids) and deleted_at is not null;
  delete from public.places where id = any(ids) and deleted_at is not null;
  return public.gc_photos(photo_ids);
end;
$$;

-- 5-3. 휴지통의 데코 분류 영구 삭제 (소속 장소는 '미분류'가 됨) → 지울 파일 경로 반환
create or replace function public.purge_deco_category(cat_id uuid)
returns text[]
language plpgsql
security invoker
set search_path = ''
as $$
declare icon uuid;
begin
  select icon_photo_id into icon from public.deco_categories where id = cat_id and deleted_at is not null;
  delete from public.deco_categories where id = cat_id and deleted_at is not null;
  if icon is null then return '{}'; end if;
  return public.gc_photos(array[icon]);
end;
$$;

-- 5-4. 데코 분류를 휴지통으로. mode = 'with_places'(소속 장소도 휴지통) | 'uncategorize'(미분류로 이동)
--      되돌리기를 위해 영향을 받은 장소 id 목록을 돌려준다.
create or replace function public.trash_deco_category(cat_id uuid, mode text)
returns uuid[]
language plpgsql
security invoker
set search_path = ''
as $$
declare affected uuid[];
begin
  if mode not in ('with_places', 'uncategorize') then
    raise exception 'invalid mode %', mode;
  end if;
  if mode = 'with_places' then
    with u as (
      update public.places set deleted_at = now()
       where deco_category_id = cat_id and deleted_at is null
      returning id)
    select coalesce(array_agg(id), '{}') into affected from u;
  else
    with u as (
      update public.places set deco_category_id = null
       where deco_category_id = cat_id and deleted_at is null
      returning id)
    select coalesce(array_agg(id), '{}') into affected from u;
  end if;
  update public.deco_categories set deleted_at = now() where id = cat_id and deleted_at is null;
  if not found then raise exception 'category not found'; end if;
  return affected;
end;
$$;

-- 5-5. 데코 분류 휴지통 되돌리기
create or replace function public.untrash_deco_category(cat_id uuid, mode text, place_ids uuid[])
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.deco_categories set deleted_at = null where id = cat_id;
  if mode = 'with_places' then
    update public.places set deleted_at = null where id = any(place_ids);
  elsif mode = 'uncategorize' then
    update public.places set deco_category_id = cat_id where id = any(place_ids) and category = 'deco';
  end if;
end;
$$;

-- 5-6. 가져오기: 추가만 수행하는 단일 트랜잭션
--   payload = { "new_categories": [{id, name, icon}], "places": [{category, deco_category_id, name, description, lat, lng, is_favorite}] }
create or replace function public.import_records(payload jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare n_cat int := 0; n_place int := 0;
begin
  insert into public.deco_categories (id, name, icon, sort_order)
  select (c->>'id')::uuid, btrim(c->>'name'), coalesce(c->>'icon', ''),
         coalesce((select max(sort_order) from public.deco_categories), 0) + row_number() over ()
    from jsonb_array_elements(coalesce(payload->'new_categories', '[]'::jsonb)) c;
  get diagnostics n_cat = row_count;

  -- 같은 시각으로 들어가면 정렬이 흔들리므로 파일 순서대로 1ms씩 차이를 둔다
  insert into public.places (category, deco_category_id, name, description, lat, lng, is_favorite, created_at)
  select p->>'category',
         nullif(p->>'deco_category_id', '')::uuid,
         btrim(p->>'name'),
         coalesce(p->>'description', ''),
         (p->>'lat')::double precision,
         (p->>'lng')::double precision,
         coalesce((p->>'is_favorite')::boolean, false),
         now() + (ord * interval '1 millisecond')
    from jsonb_array_elements(coalesce(payload->'places', '[]'::jsonb)) with ordinality as e(p, ord);
  get diagnostics n_place = row_count;

  return jsonb_build_object('categories', n_cat, 'places', n_place);
end;
$$;

-- 5-7. 현재 도감 전체를 jsonb로 (복원 안전 스냅숏·되돌리기용)
create or replace function public.current_atlas_json()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'photos',          coalesce((select jsonb_agg(to_jsonb(x) - 'owner_id') from public.photos x), '[]'::jsonb),
    'deco_categories', coalesce((select jsonb_agg(to_jsonb(x) - 'owner_id') from public.deco_categories x), '[]'::jsonb),
    'places',          coalesce((select jsonb_agg(to_jsonb(x) - 'owner_id') from public.places x), '[]'::jsonb)
  );
$$;

-- 5-8. 내부용: 도감 내용을 통째로 교체 (트랜잭션 안에서만 호출됨)
create or replace function public.replace_atlas(data jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not authenticated'; end if;

  delete from public.places where owner_id = uid;
  delete from public.deco_categories where owner_id = uid;
  delete from public.photos where owner_id = uid;

  insert into public.photos (id, kind, path, thumb_path, width, height, bytes, sha256, created_at)
  select x.id, x.kind, x.path, x.thumb_path, x.width, x.height, x.bytes, x.sha256, x.created_at
    from jsonb_to_recordset(coalesce(data->'photos', '[]'::jsonb))
         as x(id uuid, kind text, path text, thumb_path text, width int, height int, bytes int, sha256 text, created_at timestamptz);

  insert into public.deco_categories (id, name, icon, icon_photo_id, sort_order, version, created_at, updated_at, deleted_at)
  select x.id, x.name, coalesce(x.icon, ''), x.icon_photo_id, coalesce(x.sort_order, 0), coalesce(x.version, 1),
         x.created_at, x.updated_at, x.deleted_at
    from jsonb_to_recordset(coalesce(data->'deco_categories', '[]'::jsonb))
         as x(id uuid, name text, icon text, icon_photo_id uuid, sort_order int, version int,
              created_at timestamptz, updated_at timestamptz, deleted_at timestamptz);

  insert into public.places (id, category, deco_category_id, name, description, lat, lng, photo_id, is_favorite,
                             seq, version, created_at, updated_at, deleted_at)
  select x.id, x.category, x.deco_category_id, x.name, coalesce(x.description, ''), x.lat, x.lng, x.photo_id,
         coalesce(x.is_favorite, false), x.seq, coalesce(x.version, 1), x.created_at, x.updated_at, x.deleted_at
    from jsonb_to_recordset(coalesce(data->'places', '[]'::jsonb))
         as x(id uuid, category text, deco_category_id uuid, name text, description text, lat double precision,
              lng double precision, photo_id uuid, is_favorite boolean, seq bigint, version int,
              created_at timestamptz, updated_at timestamptz, deleted_at timestamptz);

  -- 등록 순번 카운터를 복원된 값 뒤로 맞춘다
  perform setval(pg_get_serial_sequence('public.places', 'seq'),
                 greatest((select coalesce(max(seq), 0) from public.places), 1));

  return jsonb_build_object(
    'places', (select count(*) from public.places),
    'deco_categories', (select count(*) from public.deco_categories),
    'photos', (select count(*) from public.photos));
end;
$$;
revoke all on function public.replace_atlas(jsonb) from public, anon;

-- 5-9. 복원 1단계: 현재 도감을 서버에 안전 스냅숏으로 저장
create or replace function public.begin_restore()
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare sid uuid;
begin
  if exists (select 1 from public.restore_snapshots where status in ('pending', 'committed')) then
    raise exception 'unfinished restore exists' using errcode = 'P0001';
  end if;
  insert into public.restore_snapshots (payload) values (public.current_atlas_json()) returning id into sid;
  return sid;
end;
$$;

-- 5-10. 복원 2단계: 도감 교체 (실패하면 트랜잭션 전체가 취소되어 원래 상태 유지)
create or replace function public.commit_restore(snapshot_id uuid, data jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare result jsonb;
begin
  perform 1 from public.restore_snapshots where id = snapshot_id and status = 'pending' for update;
  if not found then raise exception 'snapshot not pending'; end if;
  result := public.replace_atlas(data);
  update public.restore_snapshots
     set status = 'committed',
         restored_photo_paths = coalesce((
           select jsonb_agg(x) from public.photos ph, lateral unnest(array[ph.path, ph.thumb_path]) x where x is not null
         ), '[]'::jsonb)
   where id = snapshot_id;
  return result;
end;
$$;

-- 5-11. 복원 되돌리기: 스냅숏 내용으로 다시 교체. 복원 때 새로 생긴(이제 안 쓰는) 파일 경로를 돌려준다.
create or replace function public.rollback_restore(snapshot_id uuid)
returns text[]
language plpgsql
security invoker
set search_path = ''
as $$
declare snap record; leftovers text[];
begin
  select * into snap from public.restore_snapshots where id = snapshot_id and status = 'committed' for update;
  if not found then raise exception 'snapshot not committed'; end if;
  perform public.replace_atlas(snap.payload);
  select coalesce(array_agg(p), '{}') into leftovers
    from jsonb_array_elements_text(snap.restored_photo_paths) p
   where not exists (select 1 from public.photos ph where ph.path = p or ph.thumb_path = p);
  update public.restore_snapshots set status = 'rolled_back' where id = snapshot_id;
  return leftovers;
end;
$$;

-- 5-12. 복원 확정: 옛 사진 중 이제 안 쓰는 파일 경로를 돌려준다(앱이 파일 삭제)
create or replace function public.finalize_restore(snapshot_id uuid)
returns text[]
language plpgsql
security invoker
set search_path = ''
as $$
declare snap record; leftovers text[];
begin
  select * into snap from public.restore_snapshots where id = snapshot_id and status = 'committed' for update;
  if not found then raise exception 'snapshot not committed'; end if;
  select coalesce(array_agg(distinct x), '{}') into leftovers
    from jsonb_array_elements(snap.payload->'photos') ph,
         lateral unnest(array[ph->>'path', ph->>'thumb_path']) x
   where x is not null
     and not exists (select 1 from public.photos cur where cur.path = x or cur.thumb_path = x);
  update public.restore_snapshots set status = 'finalized', payload = '{}'::jsonb where id = snapshot_id;
  return leftovers;
end;
$$;

-- 5-13. 사진 업로드 도중 멈춘 복원 취소 (도감은 바뀌지 않았음)
create or replace function public.cancel_restore(snapshot_id uuid)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.restore_snapshots set status = 'cancelled', payload = '{}'::jsonb
   where id = snapshot_id and status = 'pending';
  if not found then raise exception 'snapshot not pending'; end if;
end;
$$;

revoke all on function public.gc_photos(uuid[]), public.purge_places(uuid[]), public.purge_deco_category(uuid),
  public.trash_deco_category(uuid, text), public.untrash_deco_category(uuid, text, uuid[]),
  public.import_records(jsonb), public.current_atlas_json(), public.begin_restore(),
  public.commit_restore(uuid, jsonb), public.rollback_restore(uuid), public.finalize_restore(uuid),
  public.cancel_restore(uuid), public.touch_row()
  from public, anon;
grant execute on function public.gc_photos(uuid[]), public.purge_places(uuid[]), public.purge_deco_category(uuid),
  public.trash_deco_category(uuid, text), public.untrash_deco_category(uuid, text, uuid[]),
  public.import_records(jsonb), public.current_atlas_json(), public.replace_atlas(jsonb), public.begin_restore(),
  public.commit_restore(uuid, jsonb), public.rollback_restore(uuid), public.finalize_restore(uuid),
  public.cancel_restore(uuid)
  to authenticated;
